### ISSUE TITLE
surround vorbis

### ISSUE THREAD

**Issue by diontools** [ioctlLR/NVorbis#26]
I have a surround vorbis file. NVorbis throws following exception when reading this file.
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at NVorbis.VorbisFloor.Floor1.Init(DataPacket packet)
   at NVorbis.VorbisFloor.Init(VorbisStreamDecoder vorbis, DataPacket packet)
   at NVorbis.VorbisStreamDecoder.LoadBooks(DataPacket packet)
   at NVorbis.VorbisStreamDecoder.TryInit()
   at NVorbis.VorbisReader.NewStream(Object sender, NewStreamEventArgs ea)
   at NVorbis.Ogg.ContainerReader.GatherNextPage()
   at NVorbis.Ogg.ContainerReader.Init()
   at NVorbis.VorbisReader.LoadContainer(IContainerReader containerReader)
   at NVorbis.VorbisReader..ctor(Stream stream, Boolean closeStreamOnDispose)
   at NVorbis.VorbisReader..ctor(String fileName)
```

How to reproduce
1. Download `ChID-BLITS-EBU-Narration441-16b.wav` from https://www2.iis.fraunhofer.de/AAC/multichannel.html
2. Convert to ogg: `oggenc2 ChID-BLITS-EBU-Narration441-16b.wav`
3. Open ogg file by NVorbis: `new NVorbis.VorbisReader(fileName)`

**Comment by ioctlLR** [comment]
Interesting.  I can repro the issue with the file in question, but don't have a clue why NVorbis chokes on it.  I'll have to read the libvorbis source to see what it does.
This is really an enhancement as I never tried to add true multichannel support.  I'm categorizing it as a bug because I shouldn't explicitly stated as much with an error in NVorbis itself when loading a multichannel file.  Oops...

**Comment by ioctlLR** [comment]
Y'know what?  Strike that...  I found a couple issues in the Floor 1 and Mapping 0 init code that precluded proper reading of the file.  Try 5154a8e3 as a fix.

**Comment by ioctlLR** [comment]
See [#2 in the new repository](https://github.com/NVorbis/NVorbis/issues/2).
